import React, { useState, useMemo } from 'react'
import { useStore } from '../lib/store.js'

export default function RepoToText() {
  const { repoData, archNodes } = useStore()
  const [format,   setFormat]   = useState('llm')
  const [copied,   setCopied]   = useState(false)
  const [downloaded, setDownloaded] = useState(false)

  const content = useMemo(() => {
    if (!repoData) return ''
    const sorted = [...archNodes].sort((a,b) => (a.data.path||'').localeCompare(b.data.path||''))

    if (format === 'tree') {
      const lines = [`${repoData.name}/`]
      sorted.forEach(n => {
        const depth = (n.data.path||'').split('/').length - 1
        lines.push('  '.repeat(depth) + (n.data.path||'').split('/').pop())
      })
      return lines.join('\n')
    }

    if (format === 'json') {
      return JSON.stringify({
        repository:  repoData.name,
        description: repoData.description,
        language:    repoData.language,
        stars:       repoData.stars,
        forks:       repoData.forks,
        summary:     repoData.summary,
        files:       sorted.map(n => ({ path: n.data.path, layer: n.data.layer })),
        commits:     (repoData.commits||[]).map(c => ({ sha:c.sha, message:c.message, author:c.author })),
        prs:         (repoData.prs||[]).map(p => ({ number:p.number, title:p.title, state:p.state })),
      }, null, 2)
    }

    // LLM — the main format
    const fileTree = sorted.map(n => `${n.data.path} [${n.data.layer}]`).join('\n')
    const commits  = (repoData.commits||[]).map(c => `- [${c.sha}] ${c.message} — ${c.author}`).join('\n')
    const prs      = (repoData.prs||[]).map(p => `- [${p.state}] #${p.number} ${p.title}`).join('\n')
    return `# ${repoData.name}

## Repository Overview
Language: ${repoData.language || 'Unknown'}
Stars: ${repoData.stars || 0} | Forks: ${repoData.forks || 0}
License: ${repoData.license || 'Not specified'}

## Description
${repoData.description || 'No description provided.'}

## AI Summary
${repoData.summary || ''}

## File Structure (${sorted.length} files)
${fileTree}

## Recent Commits
${commits || 'No commits available.'}

## Pull Requests
${prs || 'No PRs available.'}

---
Generated by RepoIntel · ${new Date().toISOString().split('T')[0]}
Paste this into any LLM for full codebase context.`
  }, [format, repoData, archNodes])

  function copy() {
    navigator.clipboard.writeText(content).catch(()=>{})
    setCopied(true); setTimeout(()=>setCopied(false), 2000)
  }

  function download() {
    const ext = { llm:'txt', tree:'txt', json:'json' }[format]
    const name = repoData?.name?.replace('/','_') || 'repo'
    const blob = new Blob([content], { type:'text/plain' })
    const url  = URL.createObjectURL(blob)
    const a    = Object.assign(document.createElement('a'), { href:url, download:`${name}.${ext}` })
    a.click(); URL.revokeObjectURL(url)
    setDownloaded(true); setTimeout(()=>setDownloaded(false), 2000)
  }

  const FORMATS = [
    { id:'llm',  icon:'🤖', label:'LLM-ready text', desc:'Optimised for pasting into ChatGPT, Claude, or any AI. Includes summary, file list, commits.' },
    { id:'tree', icon:'🌳', label:'File tree',       desc:'Clean directory tree with layer labels. Good for README or documentation.' },
    { id:'json', icon:'{}', label:'JSON',            desc:'Structured data: repo info, files, commits, PRs. Good for pipelines and integrations.' },
  ]

  return (
    <div style={{ display:'flex', height:'100%', overflow:'hidden' }}>

      {/* Left sidebar */}
      <div style={{ width:240, background:'var(--surface)', borderRight:'1px solid var(--border)', display:'flex', flexDirection:'column', overflow:'hidden', flexShrink:0 }}>
        <div style={{ padding:'14px 14px 10px', borderBottom:'1px solid var(--border)' }}>
          <div style={{ fontSize:14, fontWeight:600, color:'var(--text)', marginBottom:2 }}>Repo to text</div>
          <div style={{ fontSize:12, color:'var(--text3)' }}>Convert {repoData?.name} for LLMs or export</div>
        </div>

        <div style={{ padding:'12px 10px' }}>
          <div className="section-label">Output format</div>
          {FORMATS.map(f => (
            <button key={f.id} onClick={()=>setFormat(f.id)} style={{ display:'flex', gap:10, alignItems:'flex-start', width:'100%', padding:'9px 10px', marginBottom:5, background:format===f.id?'var(--blue-dim)':'var(--bg)', border:`1px solid ${format===f.id?'var(--blue)':'var(--border)'}`, borderRadius:7, cursor:'pointer', textAlign:'left', transition:'all 0.12s' }}>
              <span style={{ fontSize:17, lineHeight:1, flexShrink:0 }}>{f.icon}</span>
              <div>
                <div style={{ fontSize:13, fontWeight:600, color:format===f.id?'var(--blue)':'var(--text)', marginBottom:2 }}>{f.label}</div>
                <div style={{ fontSize:11, color:'var(--text3)', lineHeight:1.5 }}>{f.desc}</div>
              </div>
            </button>
          ))}
        </div>

        {/* Stats */}
        <div style={{ margin:'0 10px', padding:'12px', background:'var(--bg2)', border:'1px solid var(--border)', borderRadius:7, fontSize:12, color:'var(--text2)' }}>
          <div style={{ marginBottom:4 }}><strong style={{ color:'var(--text)' }}>{archNodes.length}</strong> files</div>
          <div style={{ marginBottom:4 }}><strong style={{ color:'var(--text)' }}>{content.length.toLocaleString()}</strong> characters</div>
          <div><strong style={{ color:'var(--text)' }}>~{Math.ceil(content.length/4).toLocaleString()}</strong> tokens</div>
        </div>

        <div style={{ padding:'12px 10px', borderTop:'1px solid var(--border)', marginTop:'auto', display:'flex', flexDirection:'column', gap:6 }}>
          <button onClick={copy} className="btn btn-secondary" style={{ justifyContent:'center', fontSize:13 }}>
            {copied ? '✓ Copied to clipboard' : '⎘ Copy to clipboard'}
          </button>
          <button onClick={download} className="btn btn-primary" style={{ justifyContent:'center', fontSize:13 }}>
            {downloaded ? '✓ Downloaded!' : `↓ Download .${format==='json'?'json':'txt'}`}
          </button>
        </div>
      </div>

      {/* Right — preview */}
      <div style={{ flex:1, display:'flex', flexDirection:'column', overflow:'hidden' }}>
        <div style={{ padding:'10px 16px', borderBottom:'1px solid var(--border)', background:'var(--surface)', display:'flex', alignItems:'center', gap:10, flexShrink:0 }}>
          <span style={{ fontSize:13, fontWeight:500, color:'var(--text)' }}>Preview</span>
          <span style={{ fontSize:12, color:'var(--text3)', marginLeft:'auto' }}>
            {content.length.toLocaleString()} chars · ~{Math.ceil(content.length/4).toLocaleString()} tokens
          </span>
        </div>

        <div style={{ flex:1, overflow:'auto', padding:16, background:'var(--bg)' }}>
          {!repoData ? (
            <div style={{ textAlign:'center', padding:60, color:'var(--text3)', fontSize:13 }}>
              <div style={{ fontSize:36, marginBottom:10 }}>📄</div>
              Analyze a repo first to generate the export.
            </div>
          ) : (
            <pre style={{ fontFamily:'var(--font-mono)', fontSize:12.5, lineHeight:1.7, color:'var(--text2)', background:'var(--surface)', border:'1px solid var(--border)', borderRadius:8, padding:16, margin:0, whiteSpace:'pre-wrap', wordBreak:'break-word' }}>
              {content}
            </pre>
          )}
        </div>
      </div>
    </div>
  )
}
